name: CouponAPI

services:
  mongo:
    image: mongo:latest
    container_name: coupon_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    container_name: coupon_api
    ports:
      - "1323:1323"
    environment:
      - PORT=1323
      - MONGO_URI=mongodb://mongo:mongo@mongo:27017/coupon?authSource=admin&authMechanism=SCRAM-SHA-256
    restart: always
    depends_on:
      mongo:
        condition: service_healthy

  mongo-express:
    image: mongo-express:latest
    container_name: coupon_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo
    depends_on:
      mongo:
        condition: service_healthy
